### ISSUE TITLE
Does not start with Ubuntu 14.04

### ISSUE THREAD

**Issue by isaack0815** [Storj/driveshare.org#14]
Hello there,
Drive Share does not start on Ubuntu 14:04.
After installation via the Software Center or terminal while the icon is displayed but there is no successful launch of the program.

**Comment by gordonwritescode** [comment]
Hi there, this has been resolved and will be fixed in the next release. See https://github.com/Storj/driveshare-gui/issues/45

**Comment by isaack0815** [comment]
oh, ok :-)
