### ISSUE TITLE
status.html shows payout addr instead of public wallet addr

### ISSUE THREAD

**Issue by littleskunk** [Storj/driveshare.org#8]
http://status.driveshare.org:5000/api/online shows the public wallet addr.
http://driveshare.org/status.html shows the payout addr. That is a security problem. I can write a Script to register myself with every payout addr and send 0 height information. Showing public wallet addr would be better.

**Comment by super3** [comment]
You can't change others heights in the 2.0 version. Doing this for example on: 
```http://status.driveshare.org:5000/api/height/19hZEjMAJ18fWPSApoqbNsnXdP2rMNjAJd/10``` gets you a ```Set height failed: Invalid authentication headers.```. 

However what you can do is register with every payout address, and set a height of zero. In this case the original entry and your malicious entry will show up. While this might look weird on that stats, we can make sure when we do it can't negatively affect anyone. 

We should show the payout address instead auth address. Note both are contained on ```http://status.driveshare.org:5000/api/online/json```

**Comment by littleskunk** [comment]
You are right. I did a short test and i am only able to create a second entry with 0 height but the original height is still there.

**Comment by super3** [comment]
Thanks for pointing that out, I never thought of that. Code is fine, we just need to make sure this is accounted for when we do payouts.
